name: Latest Dev Talks activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from Dev Talks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DevTalks"
          commit_message: "Updated readme with the latest dev talks data"
          feed_list: "https://feeds.buzzsprout.com/793019.rss"